import { describe, expect, it } from 'vitest';
import { defaultRegistry } from '../registry.js';

describe('defaultRegistry', () => {
	it('contains all registered components', () => {
		const types = [
			'Stack',
			'Grid',
			'Card',
			'Tabs',
			'Dialog',
			'Header',
			'Text',
			'Stat',
			'Badge',
			'Link',
			'Alert',
			'Divider',
			'Image',
			'Map',
			'DataTable',
			'TreeList',
			'BarChart',
			'LineChart',
			'AreaChart',
			'PieChart',
			'GanttChart',
			'Progress',
			'Button',
			'Input',
			'Select',
			'Textarea',
			'Checkbox',
			'RadioGroup',
			'Avatar',
			'Switch',
			'Slider',
			'Tag',
			'Empty',
			'Skeleton',
			'Spinner',
			'Accordion',
			'Drawer',
			'Breadcrumbs',
			'Stepper',
			'Toast',
			'List',
			'Carousel',
			'Descriptions',
			'Menu',
			'Combobox',
			'Rating',
			'Tooltip',
			'Calendar',
			// New components
			'AlertDialog',
			'Popover',
			'HoverCard',
			'DropdownMenu',
			'ContextMenu',
			'NavigationMenu',
			'Menubar',
			'Toggle',
			'ToggleGroup',
			'CommandPalette',
			'Field',
			'InputGroup',
			'InputOTP',
			'Form',
			'ButtonGroup',
			'NativeSelect',
			'Label',
			'Kbd',
			'Item',
			'Table',
			'Sidebar',
			'AspectRatio',
			'Collapsible',
			'ScrollArea',
			'Resizable',
		];
		for (const type of types) {
			expect(defaultRegistry.has(type), `Missing component: ${type}`).toBe(true);
		}
	});

	it('has exactly 81 components', () => {
		expect(defaultRegistry.size).toBe(81);
	});
});
